[project]
name = "geo_digital_tools"
version = "0.0.0"
authors = [
  { name = "Geoscience Data Integrations Team - GSWA", email = "gdi.contact@demirs.wa.gov.au" },
]
description = "A package designed to abstract internal common database operations."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

dependencies = [
  'SQLAlchemy==2.0.33',
  'pandas==2.2.2',
  'pyodbc==5.1.0',
  'opencensus-ext-azure==1.1.13',
  'pydantic==2.9.2',
]

[project.optional-dependencies]
tests = ['pytest==8.1.1', 'pytest-cov==5.0.0']

[project.urls]
Homepage = "https://github.com/Geological-Survey-of-Western-Australia"
Issues = "https://github.com/Geological-Survey-of-Western-Australia/issues"
